<?xml version="1.0" encoding="utf-8"?><Database Name="LaptopDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-2N2MT0S0\SQLEXPRESS;Initial Catalog=LaptopDB;Integrated Security=True" SettingsObjectName="LaptopLINQFramwork.Properties.Settings" SettingsPropertyName="LaptopDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sheet1$" Member="Sheet1_s">
    <Type Name="Sheet1_">
      <Column Name="LaptopID" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LaptopName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LaptopType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Processor" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HDD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RAM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>